"""
GAME DESIGN DURING THE FERIAS.PY SUMMER COURSE, PROVIDED BY THE PET GROUP IN THE INFORMATICS CENTER OF THE FEDERAL UNIVERSITY OF PERNAMBUCO.

CREATORS:
CARLOS AUGUSTO
CARLOS ALVAREZ
GABRIEL DIAS
GIOVANNA PASSOS
DEV. PERIODE: 01/20/2020 TO 01/24/2020 (DEADLINE)

DISCLAIMER: MOST COMMENTS AND VARIABLES ARE IN PORTUGUESE, IF YOU WANT TO TRANSLATE THEM OR CHANGE THE CODING, FEEL FREE!
"""
from time import sleep
import crafting
import textos
import imagens
import planetas
import combate

textos.texto_1()
imagens.logo()
sleep(5)
textos.limpar_tela()

textos.selecao_planetas()
